[env:esp32-s3-devkitc-1]
platform = espressif32
board = esp32-s3-devkitc-1
framework = arduino
monitor_speed = 115200
; 按实际设备端口填写，例如：
; upload_port = COMX
; monitor_port = COMX

lib_deps =
    adafruit/Adafruit GFX Library @ ^1.11.9
    adafruit/Adafruit ST7735 and ST7789 Library @ ^1.10.3
    paulstoffregen/OneWire @ ^2.3.8
    milesburton/DallasTemperature @ ^3.11.0
    bblanchon/ArduinoJson @ ^7.0.4
    esp32-camera

build_flags =
    -D CORE_DEBUG_LEVEL=5
    -D BOARD_HAS_PSRAM
    -mfix-esp32-psram-cache-issue
